version: "2.4"

services:
  scraper:
    container_name: scraper
    hostname: scraper
    build: ./apps/Metall_Scraper/
    env_file:
      - ./apps/Metall_Scraper/.env
    restart:
      always
  tg_bot:
    container_name: tg_bot
    hostname: tg_bot
    build: ./apps/Metall_Main_Bot/
    env_file:
      - ./apps/Metall_Main_Bot/.env
    restart:
      always
