version: "3.3"

services:
  scraper:
    container_name: scraper
    hostname: scraper
    build: ./apps/Metall_Scraper/
    env_file:
      - ./apps/Metall_Scraper/.env
    restart:
      always
    depends_on:
      - db


  tg_bot:
    container_name: tg_bot
    hostname: tg_bot
    build: ./apps/Metall_Main_Bot/
    env_file:
      - ./apps/Metall_Main_Bot/.env
    restart:
      always
    depends_on:
      - db


  db:
    container_name: db
    hostname: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  db:
    driver: local
